landlim/api/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns

app_name = "api"

urlpatterns = []

landlim/blog/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.i18n import i18n_patterns

app_name = 'blog'

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('', views.blog, name="blog"),
    path('details/<int:post_id>/', views.detail, name='detail'),
    path('archive/<int:year>/',
         views.PostYearArchiveIndex.as_view(), name='year'),
    path('archive/<int:year>/<int:month>/',
         views.PostMonthArchiveIndex.as_view(), name='month'),
    path('detail/<int:pk>/', views.PostDetail.as_view(), name='detail'),
    path('', views.PostList.as_view(), name='post_list'),
    path('detail/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('tag_list', views.tag_list, name="tag_list"),
    path('tag_linked_post/<int:tag_id>',views.tag_linked_post, name="tag_linked_post"),
    path('category_list', views.category_list, name="category_list"),
    path('category_linked_post/<int:category_id>', views.category_linked_post, name="category_linked_post")
]

landlim/landlim/urls.py
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from message.urls import router as message_router
from blog.api.routers import router as blog_router
from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    path('admin/', admin.site.urls),
    ## API to perform login
    path('mobile_login/', obtain_jwt_token),
    path('mobile_accounts_api/', include('accounts.api.routers')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += i18n_patterns(
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('post/', include('post.urls')),
    path('guide/', include('guide.urls')),
    path('want_todo/', include('want_todo.urls')),
    path('contact/', include('contact.urls')),
    path('notification/', include('notification.urls')),
    path('search_post/', include('search_post.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('account/', include('allauth.urls')),
    path('report/', include('report.urls')),
    path('recent/', include('recent.urls')),
    path('recruit/', include('recruit.urls')),
    path('blog/', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('api/blog/', include(blog_router.urls)),
)

landlim/blog/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django_summernote.widgets import SummernoteWidget
from enum import Enum
from django.conf import settings

## This should just be a regular developer's blog, right?
class AccessLevelChoice(Enum):
    public = "Public"
    private = "Private"

class PostQuerySet(models.QuerySet):
    def published(self):
        return self.filter(created_at__lte=timezone.now())

class Tag(models.Model):
    tag = models.CharField('Tag', max_length=50)

    def __str__(self):
        return self.tag

class Category(models.Model):
    category = models.CharField('Category', max_length=50)

    def __str__(self):
        return self.category

class Post(models.Model):
    ## Only administrator users can post.
    admin = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='Admin')
    title = models.CharField('Title', max_length=50)
    text = models.TextField('Text')
    image = models.ImageField('Image', upload_to='blog_images', blank=True, null=True)
    created_at = models.DateTimeField('Date', default=timezone.now)
    ## It would be better to be able to add more than one tag.
    tag = models.ForeignKey(Tag, verbose_name = 'Tag', on_delete=models.PROTECT)
    category = models.ForeignKey(Category, verbose_name = 'Category', on_delete=models.PROTECT)
    access_level = models.CharField('Public/Private', max_length=10, choices=[(level.name, level.value) for level in AccessLevelChoice], default='public')
    month = models.CharField('Month', max_length=10)
    date = models.CharField('Date', max_length=5)
    objects = PostQuerySet.as_manager()
    ## location information (as used by location-based services, e.g. GPS position)
    pin_x = models.FloatField('Longitude')
    pin_y = models.FloatField('Latitude')
    ## input in hiragana
    country = models.CharField(default='', max_length=20)
    prefecture = models.CharField(default='', max_length=20)
    city = models.CharField(default='', max_length=20)
    ## emotion
    emotion = models.CharField('Emotion', max_length=50)

    def __str__(self):
        return self.title

## Comment Function
class Comment(models.Model):
    text = models.TextField('Comment')
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='Post')
    username = models.CharField('Name', max_length=50)
    email = models.EmailField('Email')
    web = models.URLField('URL', blank=True, null=True)
    created_at = models.DateTimeField('Date', default=timezone.now)

    def __str__(self):
        return self.text

landlim/blog/forms.py
from django import forms
from .models import Post, Tag, Comment
from django.forms import ModelForm
from django_summernote.widgets import SummernoteWidget

class PostAddForm(forms.ModelForm):
   class Meta:
      model = Post
      fields = ['title', 'text', 'image', 'tag']
      text = forms.CharField(widget = SummernoteWidget())

class CmtForm(forms.ModelForm):
   class Meta:
      model = Comment
      fields = ['text', 'username', 'email', 'web']

landlim/blog/views.py
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post as BlogPost, Tag
from .models import Comment as BlogComment
from .models import Category as BlogCategory
from .models import Tag as BlogTag
from .forms import PostAddForm, CmtForm
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponse
from django.conf import settings
from django.core.mail import BadHeaderError, send_mail
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views import generic
from search_blog.views import *
from search_post.forms import *

def is_valid_q(q):
    return q != '' and q is not None

def blog(request):
    ## Basic information required for blog posting
    posts = BlogPost.objects.all().order_by('-created_at')
    title_or_user = request.GET.get('title_or_user')
    date_min = request.GET.get('date_min')
    date_max = request.GET.get('date_max')
    ## If there is a tag on the front side, get the tag.
    tag = request.GET.get('tag')
    ## Generating Pagination Objects
    page_obj = paginate_query(request, posts, settings.PAGE_PER_ITEM)
    ## Retrieve recent posts and recently posted images.
    recent_post = BlogPost.objects.all().order_by('-created_at')[:5]
    recent_image = BlogPost.objects.all().order_by('created_at')[:5]
    ## Retrieve all tags and categories.
    tags = BlogTag.objects.all()
    category = BlogCategory.objects.all()
    if is_valid_q(title_or_user):
        posts = posts.filter(Q(title__icontains=title_or_user)
                                | Q(user__username__icontains=title_or_user)
                                ).distinct()
    if is_valid_q(date_min):
        posts = posts.filter(created_at__gte=date_min)
    if is_valid_q(date_max):
        posts = posts.filter(created_at__lt=date_max)
    if is_valid_q(tag) and tag != 'Select a tag...':
        posts = posts.filter(tag__tag=tag)
    ## Invoking the GET method
    if request.method == "GET":
        ## Keyword Form Setup
        keyword_form = SearchPostKeywordForm(request.GET)
        ## Retrieve the 20 most recent posts.
        latest_posts = get_public_post_list(BlogPost.objects.all().order_by('-created_at')[:20])
        ## Validate the form.
        if keyword_form.is_valid():
            ## Perform a keyword search.
            search_results = get_public_post_list(search(request))
            ## Return search results if they exist.
            if len(search_results) > 0:
                messages.add_message(request, messages.SUCCESS, "Your post has been found!")
                messages.add_message(request, messages.SUCCESS, "Up to 20 found posts will be displayed on one page")
                return render(request, 'search/search_blog_by_title.html', {'latest_post_list': latest_posts, 'post_list': search_results, 'keyword_form': keyword_form, 'is_searched': True, 'tags': tags, 'category': category})
            else:
                messages.add_message(request, messages.SUCCESS, "No relevant posts found.")
                messages.add_message(request, messages.SUCCESS, "You might want to try changing to a keyword with a larger population.")
                return render(request, 'search/search_blog_by_title.html', {'latest_post_list': latest_posts, 'keyword_form': keyword_form, 'is_searched': True, 'tags': tags, 'category': category})
    keyword_form = SearchPostKeywordForm()
    return  render(request, 'blog/blog.html',
                    {'posts': posts, 'title_or_user': title_or_user, 'date_min': date_min, 'date_max': date_max, 'tag': tag, 'page_obj': page_obj, 'recent_post': recent_post, 'recent_image': recent_image, 'tags': tags, 'category': category})

def detail(request, post_id):
    ## Retrieve the details of a given submission.
    ## Get more information about the blog.
    post = get_object_or_404(BlogPost, id=post_id)
    comments = BlogComment.objects.filter(post=post).order_by('-created_at')
    liked = False
    tag = post.tag
    recent_post = BlogPost.objects.all().filter(tag=tag)
    tags = BlogTag.objects.all()
    category = BlogCategory.objects.all()
    ## Activation of comment submission form by POST method
    if request.method == "POST":
        ## Comment Form Settings
        form = CmtForm(request.POST or None)
        if form.is_valid():
            ## Comments will be accepted.
            text = request.POST.get('text')
            username = request.POST.get('username')
            email = request.POST.get('email')
            web = request.POST.get('web')
            comment = BlogComment.objects.create(
                post=post, username=username, text=text, email=email, web=web)
            comment.save()
    else:
        form = CmtForm()
    ## The GET method makes the search system work.
    if request.method == "GET":
        ## Retrieve search keywords.
        keyword_form = SearchPostKeywordForm(request.GET)
        latest_posts = get_public_post_list(BlogPost.objects.all().order_by('-created_at')[:20])
        ## Search Form Validation
        if keyword_form.is_valid():
            search_results = get_public_post_list(search(request))
            if len(search_results) > 0:
                messages.add_message(request, messages.SUCCESS, "Your post has been found!")
                messages.add_message(request, messages.SUCCESS, "Up to 20 found posts will be displayed on one page")
                return render(request, 'search/search_blog_by_title.html', {'latest_post_list': latest_posts, 'post_list': search_results, 'keyword_form': keyword_form, 'is_searched': True, 'tags': tags, 'category': category})
            else:
                messages.add_message(request, messages.SUCCESS, "No relevant posts found.")
                messages.add_message(request, messages.SUCCESS, "You might want to try changing to a keyword with a larger population.")
                return render(request, 'search/search_blog_by_title.html', {'latest_post_list': latest_posts, 'keyword_form': keyword_form, 'is_searched': True, 'tags': tags, 'category': category})
    keyword_form = SearchPostKeywordForm()
    return render(request, 'blog/details.html', {'post': post, 'form': form, 'tag_form': tag_form, 'comments': comments, 'liked': liked, 'recent_post': recent_post, 'tags': tags, 'category': category})

## Function to generate pagination
def paginate_query(request, queryset, count):
    paginator = Paginator(queryset, count)
    page = request.GET.get('page')
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    return page_obj

class PostArchiveMixin:
    model = BlogPost
    paginate_by = 10
    date_field = 'created_at'
    template_name = 'blog/post_list.html'
    allow_empty = True
    make_object_list = True

class PostArchiveIndex(PostArchiveMixin, generic.ArchiveIndexView):
    pass

class PostYearArchiveIndex(PostArchiveMixin, generic.YearArchiveView):
    pass

class PostMonthArchiveIndex(PostArchiveMixin, generic.MonthArchiveView):
    month_format = '%m'

class PostDetail(generic.DetailView):
    model = BlogPost

class PostList(generic.ListView):
    model = BlogPost

class PostDetail(generic.DetailView):
    model = BlogPost

## Get a list of tags
def tag_list(request):
    tags = BlogTag.objects.all()
    return render(request, 'blog/tag_list.html', {'tags': tags})

## Retrieve posts tied to a tag
def tag_linked_post(request, tag_id):
    tags = BlogTag.objects.all()
    tag = BlogTag.objects.filter(id=tag_id)
    post_list = BlogPost.objects.filter(tag=tag)
    return render(request, 'blog/tag_linked_post.html', {'post_list': post_list, 'tags': tags, 'tag': tag})

## Get a list of categories
def category_list(request):
    categories = BlogCategory.objects.all()
    return render(request, 'blog/tag_list.html', {'categories': categories})

## Retrieve posts tied to a category
def category_linked_post(request, category_id):
    categories = BlogCategory.objects.all()
    category = BlogCategory.objects.filter(id=category_id)
    post_list = BlogPost.objects.filter(category=category)
    return render(request, 'blog/tag_linked_post.html', {'post_list': post_list, 'categories': categories, 'category': category})

landlim/templates/blog/blog.html
{% extends 'core/front_page.html' %}
{% load static %}
{% block front_page %}
<main>
    <div class="slider-area">
        <div class="slider-bg2 hero-overly slider-height2 d-flex align-items-end">
        <div class="container">
            <div class="row">
            <div class="col-xxl-12">
                <div class="hero-caption hero-caption2">
                <h2>開発者ブログ</h2>
                </div>
            </div>
            </div>
        </div>
        </div>
    </div>
    <section class="blog_area section-padding">
        <div class="container">
        <div class="row">
            <div class="col-lg-8 mb-5 mb-lg-0">
            <div class="blog_left_sidebar"> {% for post in page_obj %}
                <article class="blog_item">
                <div class="blog_item_img"> {% if post.image %} <img class="card-img rounded-0" src="{{ post.image.url }}" alt=""> {% else %} <img class="card-img rounded-0" src="{% static 'image/school-supplies-g12fe29706_1920.jpg' %}" alt=""> {% endif %}
                    <a href="#" class="blog_item_date">
                    <h3>{{ post.date }}</h3>
                    <p>{{ post.month }}</p>
                    </a>
                </div>
                <div class="blog_details">
                    <a class="d-inline-block" href="{% url 'blog:detail' post_id=post.id %}">
                    <h2 class="blog-head" style="color: #2d2d2d;">{{ post.title | truncatechars:25 | linebreaksbr }}</h2>
                    </a>
                    <p>{{ post.text | striptags | truncatechars:25 | linebreaksbr }}</p>
                    <ul class="blog-info-link">
                    <li><a href="#"><i class="fa fa-user"></i> {{ post.admin }}</a></li>
                    <li><a href="#"><i class="fa fa-comments"></i>{{ post.category }}</a></li>
                    </ul>
                </div>
                </article> {% endfor %} {% include 'pagination.html' %} </div>
            </div>
            <div class="col-lg-4">
            <div class="blog_right_sidebar">
                <aside class="single_sidebar_widget search_widget">
                <form method="GET"> {% csrf_token %}
                    <div class="form-group m-0">
                    <div class="input-group"> <input type="text" id="id_q" name="q" class="form-control" placeholder="キーワードを入力して下さい">
                        <div class="input-group-append d-flex"> <button class="boxed-btn2" type="submit">タイトル検索</button> </div>
                    </div>
                    </div>
                </form>
                </aside>
                <aside class="single_sidebar_widget search_widget">
                <form method="GET"> {% csrf_token %}
                    <div class="form-group m-0">
                    <div class="input-group"> <input type="text" id="id_q_tag" name="q_tag" class="form-control" placeholder="タグを選択して入力して下さい">
                        <div class="input-group-append d-flex"> <button class="boxed-btn2" type="submit">タグ検索</button> </div>
                    </div>
                    </div>
                </form>
                </aside>
                <aside class="single_sidebar_widget post_category_widget">
                <h4 class="widget_title" style="color: #2d2d2d;">カテゴリー</h4>
                <ul class="list cat-list"> {% for categories in category %}
                    <li>
                    <a href="#" class="d-flex">
                        <p>{{ categories }}</p>
                    </a>
                    </li> {% endfor %} </ul>
                </aside>
                <aside class="single_sidebar_widget popular_post_widget">
                <h3 class="widget_title" style="color: #2d2d2d;">最近の投稿</h3> {% for recent in recent_post %}
                <div class="media post_item"> {% if recent.image %} <img class="recent-image" src="{{ recent.image.url }}" alt="post"> {% else %} <img class="recent-image" src="{% static 'image/school-supplies-g12fe29706_1920.jpg' %}" alt="post"> {% endif %}
                    <div class="media-body">
                    <a href="{% url 'blog:detail' post_id=recent.id %}">
                        <h3 style="color: #2d2d2d;">{{ recent.title | truncatechars:25 | linebreaksbr }}</h3>
                    </a>
                    <p>{{ recent.created_at }}</p>
                    </div>
                </div> {% endfor %} </aside>
                <aside class="single_sidebar_widget tag_cloud_widget">
                <h4 class="widget_title" style="color: #2d2d2d;">タグ</h4>
                <ul class="list"> {% for tag in tags %}
                    <li> <a href="#">{{ tag }}</a> </li> {% endfor %} </ul>
                </aside>
                <aside class="single_sidebar_widget instagram_feeds">
                <h4 class="widget_title" style="color: #2d2d2d;">Twitter</h4>
                <ul class="instagram_row flex-wrap"> <a class="twitter-timeline" href="https://twitter.com/_landlim_?ref_src=twsrc%5Etfw">Tweets by _landlim_</a>
                    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                </ul>
                </aside>
            </div>
            </div>
        </div>
        </div>
    </section>
</main>
<style>
#SaveEmailForm{
    color: #2d2d2d!important;
}
.recent-image{
    width: 80px;
    height: 80px;
    object-fit: cover;
}
</style>
{% endblock %}

landlim/templates/blog/details.html
{% extends 'core/front_page.html' %}
{% load static %}
{% block title %}{{ post.title }}{% endblock %}
{% block description %}{{ post.text | safe | truncatechars:200 | striptags }}{% endblock %}
{% block keyword %}{{ post.tag }}{% endblock %}
{% block og_title %}{{ post.title }}{% endblock %}
{% block og_description %}{{ post.text | safe | truncatechars:200 | striptags }}{% endblock %}
{% block twitter_title %}{{ post.title }}{% endblock %}
{% block twitter_description %}{{ post.text | safe | truncatechars:200 | striptags }}{% endblock %}
{% block top_image %}{% if post.image %}{{ post.image.url }}{% endif %}{% endblock %}
{% block front_page %}
<main>
    <div class="slider-area">
        <div class="slider-bg2 hero-overly slider-height2 d-flex align-items-end">
        <div class="container">
            <div class="row">
            <div class="col-xxl-12">
                <div class="hero-caption hero-caption2">
                <h2>開発者ブログ詳細</h2>
                </div>
            </div>
            </div>
        </div>
        </div>
    </div>
    <section class="blog_area single-post-area section-padding">
        <div class="container">
        <div class="row">
            <div class="col-lg-8 posts-list">
            <div class="single-post">
                <div class="feature-img"> {% if post.image %} <img class="img-fluid" src="{{ post.image.url }}" alt=""> {% else %} <img class="img-fluid" src="" alt=""> {% endif %} </div>
                <div class="blog_details">
                <h2 style="color: #2d2d2d;">{{ post.title }}</h2>
                <ul class="blog-info-link mt-3 mb-4">
                    <li><a href="#"><i class="fa fa-user"></i> {{ post.admin }}</a></li>
                    <li><a href="#"><i class="fa fa-comments"></i> {{ post.category }}</a></li>
                </ul>
                <p class="excert">{{ post.text | safe }}</p>
                </div>
            </div>
            <div class="navigation-top">
                <div class="d-sm-flex justify-content-between text-center">
                <div class="col-sm-4 text-center my-2 my-sm-0"> </div>
                <ul class="social-icons">
                    <li><a href="https://twitter.com/_landlim_"><i class="fab fa-twitter"></i></a></li>
                    <li><a href="https://www.instagram.com/_landlim_/"><i class="fab fa-instagram"></i></a></li>
                    <li><a href="https://www.facebook.com/profile.php?id=100073033226210"><i class="fab fa-facebook-f"></i></a></li>
                </ul>
                </div>
            </div>
            <div class="blog-author">
                <div class="media align-items-center"> <img src="{% static 'icon/8090A3A1-B3CA-4EDF-BB30-49FABA5A590F.jpeg' %}" alt="">
                <div class="media-body">
                    <a href="#">
                    <h4>LandLim</h4>
                    </a>
                    <p>私たちは今日も元気です。</p>
                </div>
                </div>
            </div>
            <div class="comments-area">
                <h4>コメント</h4> {% for i in comments %}
                <div class="comment-list">
                <div class="single-comment justify-content-between d-flex">
                    <div class="user justify-content-between d-flex">
                    <div class="thumb"> <img src="{% static 'image/user.png' %}" alt=""> </div>
                    <div class="desc">
                        <p class="comment">{{ i.text }}</p>
                        <div class="d-flex justify-content-between">
                        <div class="d-flex align-items-center">
                            <h5> <a href="#">{{ i.username }}</a> </h5>
                            <p class="date">{{ i.created_at }}</p>
                        </div>
                        </div>
                    </div>
                    </div>
                </div>
                </div> {% endfor %} </div>
            <div class="comment-form">
                <h4>コメント</h4>
                <form class="form-contact comment_form" method="POST" action="{% url 'blog:detail' post_id=post.id %}" id="commentForm"> {% csrf_token %}
                <div class="row">
                    <div class="col-12">
                    <div class="form-group"> <textarea class="form-control w-100" name="text" id="id_text" type="text" cols="30" rows="9" placeholder="コメント"></textarea> </div>
                    </div>
                    <div class="col-sm-6">
                    <div class="form-group"> <input class="form-control" name="username" id="id_username" type="text" placeholder="名前"> </div>
                    </div>
                    <div class="col-sm-6">
                    <div class="form-group"> <input class="form-control" name="email" id="id_email" type="email" placeholder="メールアドレス"> </div>
                    </div>
                    <div class="col-12">
                    <div class="form-group"> <input class="form-control" name="web" id="id_web" type="text" placeholder="ウェブサイト"> </div>
                    </div>
                </div>
                <div class="form-group"> <button type="submit" class="button button-contactForm btn_1 boxed-btn">コメントを投稿する</button> </div>
                </form>
            </div>
            </div>
            <div class="col-lg-4">
            <div class="blog_right_sidebar">
                <aside class="single_sidebar_widget search_widget">
                <form method="GET"> {% csrf_token %}
                    <div class="form-group m-0">
                    <div class="input-group"> <input type="text" id="id_q" name="q" class="form-control" placeholder="キーワードを入力して下さい">
                        <div class="input-group-append d-flex"> <button class="boxed-btn2" type="submit">タイトル検索</button> </div>
                    </div>
                    </div>
                </form>
                </aside>
                <aside class="single_sidebar_widget search_widget">
                <form method="GET"> {% csrf_token %}
                    <div class="form-group m-0">
                    <div class="input-group"> <input type="text" id="id_q_tag" name="q_tag" class="form-control" placeholder="タグを選択して入力して下さい">
                        <div class="input-group-append d-flex"> <button class="boxed-btn2" type="submit">タグ検索</button> </div>
                    </div>
                    </div>
                </form>
                </aside>
                <aside class="single_sidebar_widget post_category_widget">
                <h4 class="widget_title" style="color: #2d2d2d;">カテゴリー</h4>
                <ul class="list cat-list"> {% for categories in category %}
                    <li>
                    <a href="#" class="d-flex">
                        <p>{{ categories }}</p>
                    </a>
                    </li> {% endfor %} </ul>
                </aside>
                <aside class="single_sidebar_widget popular_post_widget">
                <h3 class="widget_title" style="color: #2d2d2d;">最近の投稿</h3> {% for recent in recent_post %}
                <div class="media post_item"> {% if recent.image %} <img class="recent-image" src="{{ recent.image.url }}" alt="post"> {% else %} <img class="recent-image" src="{% static 'image/school-supplies-g12fe29706_1920.jpg' %}" alt=""> {% endif %}
                    <div class="media-body">
                    <a href="blog_details.html">
                        <h3 style="color: #2d2d2d;">{{ recent.title | truncatechars:25 | linebreaksbr }}</h3>
                    </a>
                    <p>{{ recent.created_at }}</p>
                    </div>
                </div> {% endfor %} </aside>
                <aside class="single_sidebar_widget tag_cloud_widget">
                <h4 class="widget_title" style="color: #2d2d2d;">タグ</h4>
                <ul class="list"> {% for tag in tags %}
                    <li> <a href="#">{{ tag }}</a> </li> {% endfor %} </ul>
                </aside>
                <aside class="single_sidebar_widget instagram_feeds">
                <h4 class="widget_title" style="color: #2d2d2d;">Twitter</h4>
                <ul class="instagram_row flex-wrap"> <a class="twitter-timeline" href="https://twitter.com/_landlim_?ref_src=twsrc%5Etfw">Tweets by _landlim_</a>
                    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                </ul>
                </aside>
            </div>
            </div>
        </div>
        </div>
    </section>
</main>
<style>
#SaveEmailForm{
    color: #2d2d2d!important;
}
.recent-image{
    width: 80px;
    height: 80px;
    object-fit: cover;
}
</style>
{% endblock %}