landlim/api/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns

app_name = "api"

urlpatterns = []

landlim/blog/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.i18n import i18n_patterns

app_name = 'blog'

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('', views.blog, name="blog"),
    path('details/<int:post_id>/', views.detail, name='detail'),
    path('archive/<int:year>/',
         views.PostYearArchiveIndex.as_view(), name='year'),
    path('archive/<int:year>/<int:month>/',
         views.PostMonthArchiveIndex.as_view(), name='month'),
    path('detail/<int:pk>/', views.PostDetail.as_view(), name='detail'),
    path('', views.PostList.as_view(), name='post_list'),
    path('detail/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('tag_list', views.tag_list, name="tag_list"),
    path('tag_linked_post/<int:tag_id>',views.tag_linked_post, name="tag_linked_post"),
    path('category_list', views.category_list, name="category_list"),
    path('category_linked_post/<int:category_id>', views.category_linked_post, name="category_linked_post")
]

landlim/landlim/urls.py
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from message.urls import router as message_router
from blog.api.routers import router as blog_router
from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    path('admin/', admin.site.urls),
    ## API to perform login
    path('mobile_login/', obtain_jwt_token),
    path('mobile_accounts_api/', include('accounts.api.routers')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += i18n_patterns(
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('post/', include('post.urls')),
    path('guide/', include('guide.urls')),
    path('want_todo/', include('want_todo.urls')),
    path('contact/', include('contact.urls')),
    path('notification/', include('notification.urls')),
    path('search_post/', include('search_post.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('account/', include('allauth.urls')),
    path('report/', include('report.urls')),
    path('recent/', include('recent.urls')),
    path('recruit/', include('recruit.urls')),
    path('blog/', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('api/blog/', include(blog_router.urls)),
)

landlim/post/urls.py
from collections import namedtuple
from django.conf.urls import url
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from . import views

app_name = "post"

urlpatterns = [
    url(r'^add_post/$', views.add_post, name='add_post'),
    url(r'^save_your_location/$', views.save_your_location, name='save_your_location'),
    url(r'^update_post/(?P<post_pk>\d+)/$', views.update_post, name='update_post'),
    url(r'^this_post/(?P<pk>\d+)/$', views.this_post, name='this_post'),
    url(r'^delete_post/(?P<post_pk>\d+)/$', views.post_delete, name='delete_post'),
    url(r'^post_details/(?P<pk>\d+)/$', views.post_details, name='post_details'),
    path('post_details/<int:pk>/', views.PostDetail.as_view(), name='post_details'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('like/', views.like, name='like'),
    path('dislike/', views.dislike, name='dislike'),
    path('comment_like/', views.comment_like, name='comment_like'),
    path('discomment_like/', views.discomment_like, name='discomment_like'),
    path('comment/<int:pk>/', views.comment, name='comment'),
    path('liked_timeline/', views.liked_timeline, name='liked_timeline'),
    path('tag_linked_post/<int:tag_id>', views.tag_linked_post, name="tag_linked_post"),
    path('country_linked_post/<str:country>',views.country_linked_post, name="country_linked_post"),
    path('prefecture_linked_post/<str:prefecture>', views.prefecture_linked_post, name="prefecture_linked_post"),
    path('city_linked_post/<str:city>',views.city_linked_post, name="city_linked_post"),
    path('emotion_linked_post/<str:emotion>',views.emotion_linked_post, name="emotion_linked_post"),
    path('emotion_visualization', views.emotion_visualization, name="emotion_visualization"),
    path('liked_user_list/<int:pk>', views.liked_user_list, name="liked_user_list"),
]

landlim/recruit/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.i18n import i18n_patterns

app_name = 'recruit'

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('', views.recruit, name="recruit"),
    path('details/<int:post_id>/', views.detail, name='detail'),
    path('archive/<int:year>/',
         views.PostYearArchiveIndex.as_view(), name='year'),
    path('archive/<int:year>/<int:month>/',
         views.PostMonthArchiveIndex.as_view(), name='month'),
    path('detail/<int:pk>/', views.PostDetail.as_view(), name='detail'),
    path('', views.PostList.as_view(), name='post_list'),
    path('detail/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('easy_apply/<int:user_id>/', views.easy_apply, name='easy_apply'),
    path('tag_list', views.tag_list, name="tag_list"),
    path('tag_linked_post/<int:tag_id>',views.tag_linked_post, name="tag_linked_post"),
    path('category_list', views.category_list, name="category_list"),
    path('category_linked_post/<int:category_id>',views.category_linked_post, name="category_linked_post")
]

landlim/post/models.py
from email.policy import default
from re import T
from django.db import models
from django.db.models.fields.files import FileField, ImageField
from django.db.models.fields.related import ForeignKey
from django.utils import timezone
from django.conf import settings
from django.db.models import F, Max, Q
from versatileimagefield.fields import PPOIField, VersatileImageField
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
import os
from versatileimagefield.placeholder import OnDiscPlaceholderImage
from django.core.exceptions import ValidationError
from enum import Enum
from django_file_validator.validators import MaxSizeValidator
from accounts.models import User
from taggit.managers import TaggableManager
from django.core.files.base import ContentFile
from PIL import Image
from io import BytesIO
import uuid
from django.core.files.base import ContentFile
from sorl.thumbnail import get_thumbnail, delete
from django.utils.deconstruct import deconstructible

## Should do a serious error catch.

class AccessLevelChoice(Enum):
    public = "Public"
    private = "Private"

def has_no_singlequote(value):
    if "\'" in value:
        raise ValidationError(
            'Do not include single quotes (\')',
            params={'value': value},
        )

@deconstructible
class PostQuerySet(models.QuerySet):
    def published(self):
        return self.filter(created_at__lte=timezone.now())

class Video_directory_path(object):
    def video_directory_path(instance, filename):
        return 'video/{}.{}'.format(str(uuid.uuid4()), filename.split('.')[-1])

class Image_directory_path(object):
    def image_directory_path(instance, filename):
        return 'images/{}.{}'.format(str(uuid.uuid4()), filename.split('.')[-1])

## Classes for advertising users
class Video_directory_path_commercial(object):
    def video_directory_path(instance, filename):
        return 'video/{}.{}'.format(str(uuid.uuid4()), filename.split('.')[-1])

## Classes for advertising users
class Image_directory_path_commercial(object):
    def image_directory_path(instance, filename):
        return 'images/{}.{}'.format(str(uuid.uuid4()), filename.split('.')[-1])

class Post(models.Model):
    ## contributor (of written material)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='User')
    title  = models.CharField('Title', max_length=55, validators=[has_no_singlequote], blank=True)
    tags = TaggableManager(blank=True)
    text = models.TextField('Text', max_length=1500)
    ## social link
    web_link = models.URLField('WebLink', blank=True)
    twitter_link = models.URLField('TwitterLink', blank=True)
    instagram_link = models.URLField('InstagramLink', blank=True)
    ## Date Data
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(blank=True, null=True)
    ## Access level settings
    ## Public or private?
    access_level = models.CharField('Public/Private', max_length=10, choices=[(level.name, level.value) for level in AccessLevelChoice], default='public')
    pin_x = models.FloatField()
    pin_y = models.FloatField()
    objects = PostQuerySet.as_manager()
    ## Counting the number of times seen
    watched_count = models.PositiveIntegerField(default=0)
    favorite = models.ManyToManyField(User, related_name='Favorite', default=None, blank=True)
    like = models.ManyToManyField(User, related_name='Like', default=None, blank=True)
    like_count = models.BigIntegerField(default='0')
    dislike = models.ManyToManyField(User, related_name='DisLike', default=None, blank=True)
    dislike_count = models.BigIntegerField(default='0')
    bookmark_count = models.BigIntegerField(default='0')
    comment_count = models.BigIntegerField(default='0')
    country = models.CharField(default='', max_length=20)
    prefecture = models.CharField(default='', max_length=20)
    city = models.CharField(default='', max_length=50)
    ## Advertisement submission or not.
    commercial = models.CharField(default='None', max_length=5)
    ## Rough advertising genres
    food = models.CharField(default='None', max_length=5)
    shop = models.CharField(default='None', max_length=5)
    service = models.CharField(default='None', max_length=5)
    ## Tentative submission or not.
    provisional = models.CharField(default='No', max_length=5)
    ## Emotional Choice
    emotion = models.CharField('Emotion', default='Happy', max_length=10)
    ## Emotional Color
    color = models.CharField('Color', default='Happy', max_length=10)
    ## User Choice Emotion

    def update(self):
        self.updated_at = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def increment_watched_count(self):
        self.watched_count += 1
        self.update()

    def increment_comment_count(self):
        self.comment_count += 1
        self.update()

    def increment_bookmark_count(self):
        self.bookmark_count += 1
        self.update()

    def decrement_bookmark_count(self):
        self.bookmark_count -= 1
        self.update()

    def wrapper(self, *args, **kwargs):
        return

## Allow and save 3 images to be submitted.
class PostImage(models.Model):
    image = VersatileImageField(
        'PostImage',
        upload_to=Image_directory_path.image_directory_path,
        blank=True,
        null=True,
        validators=[MaxSizeValidator(100048)]
    )
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def update(self):
        self.save()

    @property
    def thumbnail_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.thumbnail['600x600'].url

    @property
    def thumbnail_100_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.thumbnail['100x100'].url

    ## Reduce the size of the image and save it.
    def save(self, *args, **kwargs):
        super(PostImage, self).save(*args, **kwargs)
        temp_icon_name = self.image.name
        if self.image.width > 405 or self.image.height > 405:
            new_width = 405
            new_height = 405
            resized = get_thumbnail(self.image, "{}x{}".format(new_width, new_height))
            name = resized.name.split('/')[-1]
            self.image.save(name, ContentFile(resized.read()), True)
            try:
                delete(temp_icon_name)
            except TypeError:
                pass

    def wrapper(self, *args, **kwargs):
        return

## Comment model to the post.
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='CommentUser')
    comment_text = models.TextField('CommentText', max_length=140, validators=[has_no_singlequote])
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='Post')
    created_at = models.DateTimeField(default=timezone.now)
    like = models.ManyToManyField(User, related_name='CommentLike', default=None, blank=True)
    like_count = models.BigIntegerField(default='0')
    dislike = models.ManyToManyField(User, related_name='CommentDisLike', default=None, blank=True)
    dislike_count = models.BigIntegerField(default='0')

    def __str__(self):
        return self.comment_text

## Video Submission
class VideoPost(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, related_name='VideoUser')
    title = models.CharField('VideoTitle', max_length=55, validators=[
                             has_no_singlequote], blank=True)
    tags = TaggableManager(blank=True)
    text = models.TextField('VideoText', max_length=1500)
    video = models.FileField(upload_to=Video_directory_path.video_directory_path,
                             blank=True, validators=[MaxSizeValidator(100048)])
    like = models.ManyToManyField(
        User, related_name='VideoLike', default=None, blank=True)
    like_count = models.BigIntegerField(default='0')
    dislike = models.ManyToManyField(
        User, related_name='VideoDisLike', default=None, blank=True)
    dislike_count = models.BigIntegerField(default='0')
    bookmark_count = models.BigIntegerField(default='0')
    created_at = models.DateTimeField(default=timezone.now)
    prefecture = models.CharField(default='', max_length=20)
    city = models.CharField(default='', max_length=20)
    pin_x = models.FloatField()
    pin_y = models.FloatField()
    ## Emotional Choice
    emotion = models.CharField('VideoEmotion', default='Happy', max_length=10)
    ## Emotional Color
    color = models.CharField('VideoColor', default='Happy', max_length=10)

## Tie emotions without permission.
## It would be interesting to be able to search by the emotion people put on it.
class UserChoiceEmotionForPost(models.Model):
    ## I don't want it to be duplicated.
    def_emotion = models.CharField('def_emotion', max_length=150, unique=True)
    def_emotion_color = models.CharField('def_emotion', max_length=150, unique=True)
    own = models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE, related_name='Own')
    supporter = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='Supporter', blank=True)
    supporter_num = models.IntegerField(default=0)
    post = models.ManyToManyField(Post, related_name='PostEmotion')

    def __str__(self):
        return self.own.username

## I want to put emotion on it.
## Discover unseen emotions.
class CreatedEmotion(models.Model):
    new_emotion = models.CharField('new_emotion', max_length=150, unique=True)
    ## Must be color coded.
    new_emotion_color = models.CharField(
        'new_emotion_color', max_length=100, unique=True, blank=True)
    emotion_maker = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='EmotionMaker')
    supporter = models.ManyToManyField(

landlim/templates/post/_image_list_create.html
{% load static %}
{% for _ in '012'|make_list %}
<div class="col-3" style="display:inline;">
  <div class="imgAspect ratio1_1">
    <img id="img{{forloop.counter0}}" src="{% static 'icon/Add_Post_LandLim.png' %}" width="50%" height="50%" alt="img" onclick="$('#file_{{forloop.counter0}}').click();" name="thumbnail_img"> 
  </div>
  <div id="edde{{forloop.counter0}}" class="text-right"></div>
</div>
{% endfor %}

landlim/templates/post/this_post.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load bootstrap4 %}
{% block content %}
<script>
  let PLACEHOLDER_IMAGE = "{% static 'icon/Add_Post_LandLim.png' %}";
</script>
<style>
label .label {
  margin-bottom: 25px;
}
</style>
{% if messages %}
<div class="position-message">
<ul class="message_ul notification message-box">
  {% for message in messages %}
  <li class="message_li notification-li">
    {{ message }}
    <i class="fas fa-trash delete"></i>
  </li>
  {% endfor %}
</ul>
</div>
{% endif %}
<div class="px-4 pt-0 pb-4 cover">
    <div class="media align-items-end profile-head">
        <div class="media-body mb-5 text-white">
            <h4 class="mt-0 mb-0">{% trans "Add Post" %}</h4>
            <p class="small mb-4"> <i class="fas fa-map-marker-alt mr-2"></i>LandLim</p>
        </div>
    </div>
</div>
<div class="px-4 pt-0 pb-2 cover_"></div>
<div class="bg-light p-4 d-flex justify-content-end text-center">
    <ul class="list-inline mb-0">
        <li class="list-inline-item">
          <h5 class="font-weight-bold mb-0 d-block margin-h5 side-h5" id="like_count">Let's Post</h5>
          <small class="text-muted">
            <i class="fas fa-share sideicon"></i>
          </small>
        </li>
    </ul>
</div>
<div class="px-4 py-3">
  <form id="contact" class="form-horizontal" role="form">
    <div class="form-group">
      <div class="col-sm-12">
        <div class="form-group">
          <p class="mb-0 left">{% trans "You can add images to your post by clicking or tapping on the photo." %}</p>
            {% if post_image_thumbnail_urls %}
              {% include "post/_image_list_update.html" %}
            {% else %}
              {% include "post/_image_list_create.html" %}
            {% endif %}
        </div>
      </div>
    </div>
  </form>
</div>
<div class="px-4 py-3">
  <form method="POST" enctype="multipart/form-data" id="contact" class="form-horizontal" role="form">
    {% csrf_token %}
    <div class="form-group">
      <div class="col-sm-12">
        <input id="id_title" name="title" type="text" placeholder="{% trans 'Title, Your input is mandatory' %}" class="form-control">
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-12">
        <textarea style="min-height: 175px;" class="form-control id_text" id="id_text" name="text" placeholder="{% trans 'Text, Your input is mandatory' %}"></textarea>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-12">
        <input id="id_tags" name="tags" type="text" placeholder="{% trans 'Tag, If there is more than one, separate them with a comma or space.' %}" class="form-control">
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-12">
        <input id="id_web_link" name="web_link" type="text" placeholder="{% trans 'Web Link' %}" class="form-control">
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-12">
        <input id="id_twitter_link" name="twitter_link" type="text" placeholder="{% trans 'Twitter Link' %}" class="form-control">
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-12">
        <input id="id_instagram" name="instagram_link" type="text" placeholder="{% trans 'Instagram Link' %}" class="form-control">
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-12 hidden">
        {% for _ in '012'|make_list %}
          <input type="hidden" name="image_{{forloop.counter0}}_exists" value=0>
        {% endfor %}
        {% for post_image_form in post_image_forms %}
        {% bootstrap_form post_image_form %}
        {% endfor %}
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-12">
        <input name="pin_x" id="id_pin_x" class="form-control" value="{{ post.pin_x }}">
        <input name="pin_y" id="id_pin_y" class="form-control" value="{{ post.pin_y }}">
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-12 icon-input-file">
        <p class="mb-0 left">{% trans "Select Video, For smartphones, the time allowed is about 60 seconds" %}</p>
        <input id="id_video" name="video" type="file" class="form-control left">
        <p class="mb-0 clear_label left">{% trans "Clear your selection" %}</p>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-12">
        <input id="id_provisional" name="provisional" type="text" value="No" class="form-control">
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-12">
        <input id="id_access_level" name="access_level" type="text" value="public" class="form-control">
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-12">
        <select class="cp_sl06" name="emotion">
          <option value="Happy">{% trans 'Happy' %}</option>
          <option value="Sad">{% trans 'Sad' %}</option>
          <option value="Disgust">{% trans 'Disgust' %}</option>
          <option value="Anger">{% trans 'Anger' %}</option>
          <option value="Fear">{% trans 'Fear' %}</option>
          <option value="Surprise">{% trans 'Surprise' %}</option>
        </select>
      </div>
    </div>
    <button type="submit" id="send" class="btn btn-block SEND">{% trans "SEND" %}</button>
  </form>
</div>
<script>
$('#id_video').on('change', function () {
  var file = $(this).prop('files')[0];
  $('#video_input').text(file.name);
});
$('.clear_label').click(function(){
  $('#id_video').val('');
  $('#video_input').text('{% trans "Not selected" %}');
  $(this).hiden();
});
</script>
<style>
.profile-head {
  transform: translateY(5rem)
}
.cover {
  background-color: #2A2E43;
  background-size: cover;
  background-repeat: no-repeat
}
.cover_ {
  background: linear-gradient(90deg, #009600 0% 25%, #006400 25% 50%, #BE8200 50% 75%, #FFB400 75% 100%);
  background-size: cover;
  background-repeat: no-repeat
}
.column {
  display: inline;
  flex-direction: column;
}
.green {
  color: #006400;
}
.red {
  color: #FF3333;
}
.image_tm {
  object-fit: cover;
  width: 327.5px;
  height: 327.5px;
  margin: 3.5px;
}
.material-icons {
  font-size: 13.5px;
}
.icon-input-files {
  text-align: left;
}
.left{
  text-align: left;
}
.side-h5 {
  font-size: 16.5px;
}
.sideicon {
  font-size: 18.5px;
  color: #006400;
}
.list-inline-item {
  text-align: right !important;
}
.margin-h5 {
  margin-bottom: 5.5px !important;
}
.button-sizing {
  margin: 0 auto;
  justify-content: center;
  width: 60.5%;
}
.form-size {
  margin: 0 auto;
  justify-content: center;
  width: 100%;
  font-size: 13.5px;
}
.font-size {
  font-size: 13.5px;
}
</style>
{% block extend_js %}
<script src="{% static 'js/message.js' %}"></script>
{% endblock %}
{% endblock %}

landlim/templates/post/update_post.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% load i18n %}
{% block content %}
<script>
  let PLACEHOLDER_IMAGE = "{% static 'icon/Add_Post_LandLim.png' %}";
</script>
<style>
  label.label {
    margin-bottom: 25px;
  }
</style>
{% if messages %}
<div class="position-message">
<ul class="message_ul notification message-box">
  {% for message in messages %}
  <li class="message_li notification-li">
    {{ message }}
    <i class="fas fa-trash delete"></i>
  </li>
  {% endfor %}
</ul>
</div>
{% endif %}
<div class="bg-white shadow rounded overflow-hidden contain-card-body">
  <div class="px-4 pt-0 pb-4 cover_">
      <div class="media align-items-end profile-head">
          <div class="media-body mb-5 text-white">
              <h4 class="mt-0 mb-0">{% trans "Edit Post" %}</h4>
              <p class="small mb-4"> <i class="fas fa-map-marker-alt mr-2"></i>LandLim</p>
          </div>
      </div>
  </div>
  <div class="bg-light p-4 d-flex justify-content-end text-center">
      <ul class="list-inline mb-0">
          <li class="list-inline-item">
            <h5 class="font-weight-bold mb-0 d-block margin-h5" id="like_count">Let's Edit Post</h5>
            <small class="text-muted">
              <i class="fas fa-edit sideicon"></i>
            </small>
          </li>
      </ul>
  </div>
  <div class="px-4 py-3">
    <h5 class="mb-0">Edit Post Form</h5>
    <form method="POST" action="{% url 'post:update_post' post_pk=post.pk %}" enctype="multipart/form-data" id="contact" class="form-horizontal" role="form">
      {% csrf_token %}
      <div class="form-group">
        <div class="col-sm-12">
          <input id="id_title" name="title" type="text" value="{{ post.title }}" class="form-control">
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-12">
          <p class="mb-0 left">{% trans "If you do not want to change the text, copy-paste the previous text." %}<br>{{ post.text | safe | linebreaksbr | truncatechars:110 }}</p>
          <textarea style="min-height: 175px;" class="form-control id_text" id="id_text" name="text" placeholder="Text"></textarea>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-12">
        {% if post.web_link %}
          <input id="id_web_link" name="web_link" type="text" value="{{ post.web_link }}" class="form-control">
        {% else %}
          <input id="id_web_link" name="web_link" type="text" placeholder="{% trans 'Web Link' %}" class="form-control">
        {% endif %}
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-12">
        {% if post.twitter_link %}
          <input id="id_twitter_link" name="twitter_link" type="text" value="{{ post.twitter_link }}" class="form-control">
        {% else %}
          <input id="id_twitter_link" name="twitter_link" type="text" placeholder="{% trans 'Twitter Link' %}" class="form-control">
        {% endif %}
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-12">
        {% if instagram_link %}
          <input id="id_instagram_link" name="instagram_link" type="text" value="{{ post.instagram_link }}" class="form-control">
        {% else %}
          <input id="id_instagram_link" name="instagram_link" type="text" placeholder="{% trans 'Instagram Link' %}" class="form-control">
        {% endif %}
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-12 hidden">
          <input name="pin_x" id="id_pin_x" class="form-control" value="{{ post.pin_x }}">
          <input name="pin_y" id="id_pin_y" class="form-control" value="{{ post.pin_y }}">
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-12">
          <input id="id_access_level" name="access_level" type="text" value="public" class="form-control">
        </div>
      </div>
      <button type="submit" id="send" class="btn btn-block SEND">{% trans "SEND" %}</button>
    </form>
  </div>
</div>
<style>
.profile-head {
  transform: translateY(5rem)
}
 .cover_ {
  background: linear-gradient(-15.5deg, #BE8200 20%, #FFB400 20% 40%, #009600 40% 60%, #006400 60% 80%);
  background-size: cover;
  background-repeat: no-repeat
}
.column {
  display: inline;
  flex-direction: column;
}
.green {
  color: #006400;
}
.red {
  color: #FF3333;
}
.image_tm {
  object-fit: cover;
  width: 327.5px;
  height: 327.5px;
  margin: 3.5px;
}
.material-icons {
  font-size: 13.5px;
}
.icon-input-files {
  text-align: left;
}
.left{
  text-align: left;
}
.sideicon {
  font-size: 20.5px;
  color: #006400;
}
.list-inline-item {
  text-align: right !important;
}
.margin-h5 {
  margin-bottom: 5.5px !important;
}
</style>
{% block extend_js %}
<script src="{% static 'js/message.js' %}"></script>
{% endblock %}
{% endblock %}