landlim/api/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns

app_name = "api"

urlpatterns = []

landlim/contact/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include

app_name = "contact"

urlpatterns = [
    url(r'^$', views.post_contact, name='post_contact'),
    path('i18n/', include('django.conf.urls.i18n')),
]

landlim/guide/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

app_name = "guide"

urlpatterns = [
    url(r'^landlim_guide$', views.landlim_guide, name='landlim_guide'),
    url(r'^landlim_faqs$', views.landlim_faqs, name='landlim_faqs'),
    url(r'^landlim_about$', views.landlim_about, name='landlim_about'),
    path('i18n/', include('django.conf.urls.i18n')),
]

landlim/landlim/urls.py
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from message.urls import router as message_router
from blog.api.routers import router as blog_router
from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    path('admin/', admin.site.urls),
    ## API to perform login
    path('mobile_login/', obtain_jwt_token),
    path('mobile_accounts_api/', include('accounts.api.routers')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += i18n_patterns(
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('post/', include('post.urls')),
    path('guide/', include('guide.urls')),
    path('want_todo/', include('want_todo.urls')),
    path('contact/', include('contact.urls')),
    path('notification/', include('notification.urls')),
    path('search_post/', include('search_post.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('account/', include('allauth.urls')),
    path('report/', include('report.urls')),
    path('recent/', include('recent.urls')),
    path('recruit/', include('recruit.urls')),
    path('blog/', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('api/blog/', include(blog_router.urls)),
)

landlim/post/urls.py
from collections import namedtuple
from django.conf.urls import url
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from . import views

app_name = "post"

urlpatterns = [
    url(r'^add_post/$', views.add_post, name='add_post'),
    url(r'^save_your_location/$', views.save_your_location, name='save_your_location'),
    url(r'^update_post/(?P<post_pk>\d+)/$', views.update_post, name='update_post'),
    url(r'^this_post/(?P<pk>\d+)/$', views.this_post, name='this_post'),
    url(r'^delete_post/(?P<post_pk>\d+)/$', views.post_delete, name='delete_post'),
    url(r'^post_details/(?P<pk>\d+)/$', views.post_details, name='post_details'),
    path('post_details/<int:pk>/', views.PostDetail.as_view(), name='post_details'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('like/', views.like, name='like'),
    path('dislike/', views.dislike, name='dislike'),
    path('comment_like/', views.comment_like, name='comment_like'),
    path('discomment_like/', views.discomment_like, name='discomment_like'),
    path('comment/<int:pk>/', views.comment, name='comment'),
    path('liked_timeline/', views.liked_timeline, name='liked_timeline'),
    path('tag_linked_post/<int:tag_id>', views.tag_linked_post, name="tag_linked_post"),
    path('country_linked_post/<str:country>',views.country_linked_post, name="country_linked_post"),
    path('prefecture_linked_post/<str:prefecture>', views.prefecture_linked_post, name="prefecture_linked_post"),
    path('city_linked_post/<str:city>',views.city_linked_post, name="city_linked_post"),
    path('emotion_linked_post/<str:emotion>',views.emotion_linked_post, name="emotion_linked_post"),
    path('emotion_visualization', views.emotion_visualization, name="emotion_visualization"),
    path('liked_user_list/<int:pk>', views.liked_user_list, name="liked_user_list"),
]

landlim/recent/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns

app_name = "recent"

urlpatterns = [
    path('timeline/',views.recent, name='recent'),
    path('map/', views.local_map, name='local_map'),
    path('video/', views.recent_video, name='recent_video'),
    path('i18n/', include('django.conf.urls.i18n')),
]

landlim/templates/landlim_sidebar.html
{% load static %}
{% load i18n %}
<nav id="sidebar" class="sidebar-wrapper">
    <div class="sidebar-content">
      <div class="sidebar-brand">
        <a class="title" style="color: #000000;" href="{% url 'index' %}">{% trans "LandLim" %}</a>
        <div id="close-sidebar">
          <i class="fas fa-times"></i>
        </div>
      </div>
      <div class="sidebar-header">
        <div class="user-pic">
          {% if request.user.icon_url %}
          <img class="img-responsive img-rounded" src="{{ request.user.icon_url }}" alt="User picture">
          {% else %}
          <img class="img-responsive img-rounded" src="{% static 'icon/LandLim_Human.png' %}" alt="User picture">
          {% endif %}
        </div>
        <div class="user-info">
          <span class="user-name">
            {% if request.user.is_authenticated %}
            {% if request.user.nickname %}
            <strong>{{ request.user.nickname }}</strong>
            {% else %}
            <strong>{{ request.user.username }}</strong>
            {% endif %}
            {% else %}
            <strong>{% trans "Guest User" %}</strong>
            {% endif %}
          </span>
          <span class="user-role">{% trans "User" %}</span>
          <span class="user-status">
            <i class="fas fa-user"></i>
            <span>{% trans "Online" %}</span>
          </span>
        </div>
      </div>
      <div class="sidebar-menu">
        <ul>
          <li class="header-menu">
            <span style="color: #006400;">{% trans "MENU" %}</span>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fas fa-user"></i>
              <span>{% trans "ACCOUNTS" %}</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                {% if request.user.is_authenticated %}
                <li>
                  <a href="{% url 'accounts:own_page' %}">{% trans "MY PAGE" %}</a>
                </li>
                <li>
                  <a href="{% url 'accounts:following_list' %}">{% trans "FOLLOWS" %}</a>
                </li>
                <li>
                  <a href="{% url 'accounts:follower_list' %}">{% trans "FOLLOWERS" %}</a>
                </li>
                <li>
                  <a href="{% url 'accounts:edit_accounts' %}">{% trans "EDIT" %}</a>
                </li>
                <li>
                  <a href="{% url 'accounts:get_your_position' %}">{% trans "GET POSITION" %}</a>
                </li>
                <li>
                  <a href="{% url 'accounts:logout_accounts' %}">{% trans "LOG OUT" %}</a>
                </li>
                {% else %}
                <li>
                  <a href="{% url 'accounts:login_accounts' %}">{% trans "LOG IN" %}</a>
                </li>
                <li>
                  <a href="{% url 'accounts:signup_accounts' %}">{% trans "SIGN UP" %}</a>
                </li>
                {% endif %}
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fas fa-map-marker-alt"></i>
              <span>{% trans  "POST" %}</span>
              <span style="background-color: #009600;" class="badge badge-pill badge-danger">{% trans "LandLim!" %}</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="{% url 'post:add_post' %}">{% trans "ADD" %}</a>
                </li>
                <li>
                  <a href="{% url 'post:save_your_location' %}">{% trans "SAVE LOCATION" %}</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fas fa-broadcast-tower"></i>
              <span>{% trans "RECENT" %}</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="{% url 'recent:local_map' %}">{% trans "MAP" %}</a>
                </li>
                <li>
                  <a href="{% url 'recent:recent' %}">{% trans "TIME LINE" %}</a>
                </li>
                <li>
                  <a href="{% url 'recent:recent_video' %}">{% trans "VIDEO" %}</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fas fa-handshake"></i>
              <span>{% trans "FRIENDS" %}</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="{% url 'accounts:friends_map' %}">{% trans "MAP" %}</a>
                </li>
                <li>
                  <a href="{% url 'accounts:friends_timeline' %}">{% trans "TIME LINE" %}</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fas fa-bookmark"></i>
              <span>{% trans "BOOKMARK" %}</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="{% url 'bookmark:bookmark_map' %}">{% trans "MAP" %}</a>
                </li>
                <li>
                  <a href="{% url 'bookmark:bookmark' %}">{% trans "LIST" %}</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="far fa-thumbs-up"></i>
              <span>{% trans "LIKE" %}</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="{% url 'accounts:like_map' %}">{% trans "MAP" %}</a>
                </li>
                <li>
                  <a href="{% url 'accounts:like_list' %}">{% trans "LIST" %}</a>
                </li>
                <li>
                  <a href="{% url 'post:liked_timeline' %}">{% trans "TIME LINE" %}</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fas fa-info"></i>
              <span>{% trans "GUIDE" %}</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="{% url 'guide:landlim_guide' %}">{% trans "GUIDE" %}</a>
                </li>
                <li>
                  <a href="{% url 'guide:landlim_faqs' %}">{% trans "FQA" %}</a>
                </li>
                <li>
                  <a href="{% url 'guide:landlim_about' %}">{% trans "ABOUT LANDLIM" %}</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-globe"></i>
              <span>{% trans "SEARCH MAPS" %}</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="{% url 'search_post:search_refine' %}">{% trans "総合検索システム" %}</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fas fa-cog"></i>
              <span>{% trans "SETTINGS" %}</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="{% url 'guide:landlim_guide' %}">{% trans "ACCOUNT SETTING" %}</a>
                </li>
                <li>
                  <a href="{% url 'guide:landlim_faqs' %}">{% trans "PRIVACY" %}</a>
                </li>
                <li>
                  <a href="{% url 'guide:landlim_about' %}">{% trans "BASIC SETTINGS" %}</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fas fa-cog"></i>
              <span>{% trans "WANT TO DO" %}</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="{% url 'want_todo:want_todo_list' %}">{% trans "WANT TO DO LIST" %}</a>
                </li>
                <li>
                  <a href="{% url 'want_todo:add_want_todo' %}">{% trans "ADD WANT TO DO" %}</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="header-menu">
            <span style="color: #006400;">{% trans "EXTRA" %}</span>
          </li>
          <li>
            <a href="{% url 'contact:post_contact' %}">
              <i class="fas fa-envelope"></i>
              <span>{% trans "CONTACT" %}</span>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="fas fa-share-alt"></i>
              <span>{% trans "SHARE" %}</span>
            </a>
          </li>
          <li>
            <a href="https://twitter.com/landlim_">
              <i class="fab fa-twitter"></i>
              <span>{% trans "TWITTER" %}</span>
            </a>
          </li>
          <li>
            <a href="https://www.instagram.com/landlim_/">
              <i class="fab fa-instagram"></i>
              <span>{% trans "INSTAGRAM" %}</span>
            </a>
          </li>
          <li>
            <a href="https://www.facebook.com/profile.php?id=100073033226210">
              <i class="fab fa-facebook"></i>
              <span>{% trans "FACEBOOK" %}</span>
            </a>
          </li>
          <li>
            <form action="{% url 'set_language' %}" method="post">
              {% csrf_token %}
              <input name="next" type="hidden" value="{{ redirect_to }}">
              <select class="custom-select" name="language">
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                {% for language in languages %}
                <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                  {{ language.name_local }}
                </option>
                {% endfor %}
              </select>
              <button type="submit" id="send" class="btn btn-block SEND">{% trans "CHANGE" %}</button>
            </form>
          </li>
        </ul>
      </div>
      <div class="footer-image"></div>
    </div>
    <footer class="text-center">
      <div class="mb-2">
        <small>
          {% trans "ç 2022 LandLim" %}
        </small>
      </div>
    </footer>
</nav>
<style>
.cp_ipselect {
	position: relative;
	width: 80.5%;
	margin: 2em auto;
	text-align: center;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";;
}
.cp_sl06 {
	position: relative;
	font-family: inherit;
	background-color: transparent;
	width: 100%;
	padding: 10px 10px 10px 0;
	font-size: 18px;
	border-radius: 0;
	border: none;
	border-bottom: 1px solid rgba(0,0,0, 0.3);
}
.cp_sl06:focus {
	outline: none;
	border-bottom: 1px solid rgba(0,0,0, 0);
}
.cp_ipselect .cp_sl06 {
	appearance: none;
	-webkit-appearance:none
}
.cp_ipselect select::-ms-expand {
	display: none;
}
.cp_ipselect:after {
	position: absolute;
	top: 18px;
	right: 10px;
	width: 0;
	height: 0;
	padding: 0;
	content: '';
	border-left: 6px solid transparent;
	border-right: 6px solid transparent;
	border-top: 6px solid rgba(0, 0, 0, 0.3);
	pointer-events: none;
}
.cp_sl06_selectlabel {
	color: rgba(0,0,0, 0.5);
	font-size: 18px;
	font-weight: normal;
	position: absolute;
	pointer-events: none;
	left: 0;
	top: 10px;
	transition: 0.2s ease all;
}
.cp_sl06:focus ~ .cp_sl06_selectlabel, .cp_sl06:valid ~ .cp_sl06_selectlabel {
	color: #009600;
	top: -20px;
	transition: 0.2s ease all;
	font-size: 14px;
}
.cp_sl06_selectbar {
	position: relative;
	display: block;
	width: 100%;
}
.cp_sl06_selectbar:before, .cp_sl06_selectbar:after {
	content: '';
	height: 2px;
	width: 0;
	bottom: 1px;
	position: absolute;
	background: #009600;
	transition: 0.2s ease all;
}
.cp_sl06_selectbar:before {
	left: 50%;
}
.cp_sl06_selectbar:after {
	right: 50%;
}
.cp_sl06:focus ~ .cp_sl06_selectbar:before, .cp_sl06:focus ~ .cp_sl06_selectbar:after {
	width: 50%;
}
.cp_sl06_highlight {
	position: absolute;
	top: 25%;
	left: 0;
	pointer-events: none;
	opacity: 0.5;
}
.SEND{
  width: 65.5%;
  margin: 0 auto;
  font-size: 15.5px !important;
  margin-bottom: 35.55px !important;
}
.title{
  font-size: 16.5px;
  text-transform: none !important;
  color: #2A2E43;
}
</style>

landlim/templates/pagination.html
<nav class="blog-pagination justify-content-center d-flex">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous">
                    <i class="ti-angle-left"></i>
                </a>
            </li>
        {% else %}
            <li class="page-item">
                <a href="#" class="page-link" aria-label="Previous">
                    <i class="ti-angle-left"></i>
                </a>
            </li>
        {% endif %}
            <li class="page-item">
                <a href="?page={{ page_obj.paginator.page_range }}" class="page-link">{{ page_obj.number }}</a>
            </li>
        {% if page_obj.has_next %}
            <li class="page-item">
                <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
                    <i class="ti-angle-right"></i>
                </a>
            </li>
        {% else %}
            <li class="page-item">
                <a href="#" class="page-link" aria-label="Next">
                    <i class="ti-angle-right"></i>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>