landlim/accounts/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns

app_name = "accounts"

urlpatterns = [
    url(r'^signup/$',views.signup_accounts, name='signup_accounts'),
    url(r'^login/$',views.login_accounts, name='login_accounts'),
    url(r'^logout/$', views.logout_accounts, name='logout_accounts'),
    url(r'^own_page/$', views.own_page, name='own_page'),
    url(r'^edit/$', views.edit_accounts, name='edit_accounts'),
    url(r'^others_page/(?P<user_pk>\d+)/$', views.others_page, name='others_page'),
    path('activate/<slug:uidb64>/<slug:token>/',views.activation, name='activation'),
    url(r'^password/reset/$', views.password_reset, name='reset-password'),
    url(r'^password/reset/done/$', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='reset-password-done'),
    path('reset/<uidb64>/<token>/', views.password_reset_confirm, name='reset-password-confirm'),
    url(r'password/reset/complete/$', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_from_key_done.html'), name='reset-password-complete'),
    url(r'^delete/$', views.delete_accounts, name='delete_accounts'),
    url(r'^like_list/$', views.like_list, name='like_list'),
    url(r'^like_map/$', views.like_map, name='like_map'),
    path('follow_unfollow/', views.follow_unfollow, name='follow_unfollow'),
    path('block_unblock/', views.block_unblock, name='block_unblock'),
    path('following/', views.following_list, name='following_list'),
    path('follower/', views.follower_list, name='follower_list'),
    path('friends_map/', views.friends_map, name='friends_map'),
    path('friends_timeline/', views.friends_timeline, name='friends_timeline'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('get_your_position/', views.get_your_position, name="get_your_position"),
]

landlim/api/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns

app_name = "api"

urlpatterns = []

landlim/landlim/urls.py
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from message.urls import router as message_router
from blog.api.routers import router as blog_router
from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    path('admin/', admin.site.urls),
    ## API to perform login
    path('mobile_login/', obtain_jwt_token),
    path('mobile_accounts_api/', include('accounts.api.routers')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += i18n_patterns(
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('post/', include('post.urls')),
    path('guide/', include('guide.urls')),
    path('want_todo/', include('want_todo.urls')),
    path('contact/', include('contact.urls')),
    path('notification/', include('notification.urls')),
    path('search_post/', include('search_post.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('account/', include('allauth.urls')),
    path('report/', include('report.urls')),
    path('recent/', include('recent.urls')),
    path('recruit/', include('recruit.urls')),
    path('blog/', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('api/blog/', include(blog_router.urls)),
)

landlim/want_todo/urls.py
from accounts.views import delete_accounts
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = "want_todo"

urlpatterns = [
    path('', views.want_todo_list, name='want_todo_list'),
    path('map/', views.want_todo_map, name='want_todo_map'),
    path('add_want_todo/', views.add_want_todo, name='add_want_todo'),
    path('delete_want_todo/<int:pk>/', views.delete_want_todo, name='delete_want_todo'),
    path('i18n/', include('django.conf.urls.i18n')),
]

landlim/want_todo/models.py
from __future__ import unicode_literals
from email.policy import default
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.conf import settings

class WantToDo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='WantToDoUser')
    want_todo_title = models.CharField('WantToDoTitle', max_length=100)
    want_todo_text = models.CharField('WantToDoText', max_length=100)
    created_at = models.DateTimeField(default=timezone.now)
    pin_x = models.FloatField()
    pin_y = models.FloatField()
    ## the other party
    checked = models.BooleanField('is_Check', default=None)
    ## Finished todo list
    finished = models.BooleanField('is_Finished', default=None)

    def __str__(self):
        return self.want_todo_text

class WantToDoPoint(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='WantToDoUserPoint')
    point = models.FloatField(default=0)

    def __str__(self):
        return self.point

landlim/want_todo/forms.py
from django import forms
from .models import WantToDo
from django.forms import ModelForm

class WantToDoAddForm(forms.ModelForm):
   class Meta:
      model = WantToDo
      fields = ['want_todo_title', 'want_todo_text', 'pin_x', 'pin_y']

landlim/want_todo/views.py
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404, redirect
from .models import WantToDo, WantToDoPoint
from .forms import WantToDoAddForm
from django.contrib import messages
from django.http import HttpResponse
from django.utils.translation import gettext_lazy as _
from post.models import Post
from accounts.models import User
from geopy.distance import great_circle

## Perform todo list display.
def want_todo_list(request):
    todo = WantToDo.objects.all().order_by('created_at')
    return render(request, 'want_todo/want_todo_list.html', {'todo': todo})

## You can see where you want to go.
def want_todo_map(request):
    todo = WantToDo.objects.all().order_by('created_at')
    return render(request, 'want_todo/want_todo_map.html', {'todo': todo})

## The list of things you want to do can be crossed off.
## It would be better not to let the map load again.
def delete_want_todo(request, pk):
    todo = get_object_or_404(WantToDo, pk=pk)
    todo_user_id = todo.user.id
    if todo_user_id != request.user.id:
        messages.add_message(request, messages.ERROR, _("That to-do list may not be yours!"))
        return HttpResponse(_("You don't seem to have permission to edit your to-do list"))
    else:
        todo = get_object_or_404(WantToDo, pk=pk)
        todo.delete()
        todo = WantToDo.objects.all().order_by('-created_at')
        messages.add_message(request, messages.SUCCESS, _("Things to do have been removed"))
        messages.add_message(request, messages.SUCCESS, _("Thank you for your time"))
    return render(request, 'want_todo/want_todo_list.html', {'todo': todo})

## Add a todo list.
def add_want_todo(request):
    if request.method == "POST":
        form = WantToDoAddForm(request.POST or None)
        if form.is_valid():
            title = request.POST.get('want_todo_title')
            text = request.POST.get('want_todo_text')
            pin_x= request.POST.get("pin_x")
            pin_y = request.POST.get("pin_y")
            todo = WantToDo.objects.create(
                user=request.user, title=title, text=text, pin_x=pin_x, pin_y=pin_y)
            todo.save()
            todo = WantToDo.objects.all().order_by('-created_at')
            messages.add_message(request, messages.SUCCESS, _("Added things to do"))
            ## Redirection would be better.
            return render(request, 'want_todo_list/want_todo_list.html', {'todo': todo})
        else:
            messages.add_message(request, messages.ERROR, _("I couldn't add anything to do"))
            messages.add_message(request, messages.ERROR, _("Character count may be a problem"))
            messages.add_message(request, messages.ERROR, _("Are you already logged in to LandLim?"))
    else:
        form = WantToDoAddForm()
    return render(request, 'want_todo/add_want_todo.html', {'form':form})

## Check if they have been there.
## It would be nice to be able to press a check button to obtain points.
def check_and_give_point(request, user_pk, post_pk, want_todo_pk):
    user = User.objects.filter(pk=user_pk)
    post = Post.objects.filter(pk=post_pk)
    want_todo = WantToDo.objects.filter(pk=want_todo_pk)
    if WantToDoPoint.objects.filter(user=user).exist():
        point = WantToDoPoint.objects.filter(user=user)
    else:
        point = WantToDoPoint.objects.create(user=user)
        point.save()
        point = WantToDoPoint.objects.filter(user=user)
    post_dis = (post.pin_y,post.pin_x)
    want_todo_dis = (want_todo.pin_y,want_todo.pin_x)
    dis = great_circle(post_dis, want_todo_dis).km
    if dis < 10:
        point.point += 10
        return True
    elif 10 <= dis < 50:
        point.point += 20
        return True
    elif 50 <= dis < 100:
        point.point += 50
        return True
    elif 100 <= dis < 500:
        point.point += 100
        return True
    elif 500 <= dis < 1000:
        point.point += 200
        return True
    elif 1000 <= dis:
        point.point += 500
        return True
    else:
        return None

landlim/templates/want_todo/add_want_todo.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load i18n %}
{% load static %}
{% block content %}
{% if messages %}
<div class="position-message">
<ul class="message_ul notification message-box">
  {% for message in messages %}
  <li class="message_li notification-li">
    {{ message }}
    <i class="fas fa-trash delete"></i>
  </li>
  {% endfor %}
</ul>
</div>
{% endif %}
<div class="bg-white shadow rounded overflow-hidden contain-card-body">
  <div class="px-4 pt-0 pb-4 cover_">
      <div class="media align-items-end profile-head">
          <div class="media-body mb-5 text-white">
              <h4 class="mt-0 mb-0">{% trans "ToDo List" %}</h4>
              <p class="small mb-4"> <i class="fas fa-map-marker-alt mr-2"></i>LandLim</p>
          </div>
      </div>
  </div>
  <div class="bg-light p-4 d-flex justify-content-end text-center">
      <ul class="list-inline mb-0">
          <li class="list-inline-item">
            <h5 class="font-weight-bold mb-0 d-block margin-h5" id="like_count">Let's Make a ToDoList</h5>
            <small class="text-muted">
              <i class="fas fa-list-ul sideicon"></i>
            </small>
          </li>
      </ul>
  </div>
  <div class="px-4 py-3">
    <form method="POST" action="{% url 'want_todo:add_want_todo' %}" id="contact" class="form-horizontal" role="form">
      {% csrf_token %}
      <div class="form-group">
        <div class="col-sm-12">
          <textarea style="min-height: 175px;" class="form-control id_text" id="id_text" name="text" placeholder="{% trans 'Text, Max 100 characters' %}"></textarea>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-12">
          <p id="pin_x"></p>
          <p id="pin_y"></p>
        </div>
      </div>
      <button type="submit" id="send" name="send" class="btn btn-block">{% trans "SEND" %}</button>
    </form>
  </div>
  <div class="px-1 py-3">
    <div class="row column">
      <div class="col-lg-12 mb-2">
        <div class="container" id="mapid"></div>
      </div>
    </div>
  </div>
</div>
<style>
.profile-head {
  transform: translateY(5rem)
}
 .cover_ {
  background: linear-gradient(-15.5deg, #BE8200 20%, #FFB400 20% 40%, #009600 40% 60%, #006400 60% 80%);
  background-size: cover;
  background-repeat: no-repeat
}
.column {
  display: inline;
  flex-direction: column;
}
.green {
  color: #006400;
}
.red {
  color: #FF3333;
}
.image_tm {
  object-fit: cover;
  width: 327.5px;
  height: 327.5px;
  margin: 3.5px;
}
.material-icons {
  font-size: 13.5px;
}
.sideicon {
  font-size: 20.5px;
  color: #006400;
}
.list-inline-item {
  text-align: right !important;
}
.margin-h5 {
  margin-bottom: 5.5px !important;
}
</style>
<script>
var mymap = L.map('mapid', {preferCanvas: true,});
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
minZoom: 8,
maxZoom: 19,
attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, '
}).addTo(mymap);
var pulsingIcon2 = L.icon.pulse({
iconSize:[20,20]
,color:'#006400'
,fillColor:'#009600'
,heartbeat: 2
});
function onLocationFound(e){
  L.Icon.Default.imagePath = 'https://unpkg.com/leaflet@1.3.1/dist/images/';
  L.marker(e.latlng, {icon:pulsingIcon2}).addTo(mymap);
}
function onLocationError(e){
  alert("Could not retrieve current location. 現在地を取得できませんでした。" + e.message);
}
mymap.on('locationfound', onLocationFound);
mymap.on('locationerror', onLocationError);
mymap.on('click', function(e) {
    lat = e.latlng.lat;
    lng = e.latlng.lng;
    var elem = document.getElementById("pin_x");
    elem.innerHTML = "<input type='text' name='pin_x' id='pin_x' class='form-control' value = " + lat + ">";
    var elem = document.getElementById("pin_y");
    elem.innerHTML = "<input type='text' name='pin_y' id='pin_y' class='form-control' value = " + lng + ">";
} );
mymap.locate({setView: true, minZoom: 8, maxZoom: 19, timeout: 20000});
mymap.zoomControl.setPosition('bottomright');
mymap.sharelocationControl.setPosition('bottomright');
navigator.geolocation.getCurrentPosition(InputPinLocation,onLocationError);
</script>
{% block extend_js %}
<script src="{% static 'js/message.js' %}"></script>
{% endblock %}
{% endblock %}

landlim/templates/want_todo/want_todo_list.html
{% extends 'base.html' %}
{% load show_pagenated_post_list %}
{% load show_post_list %}
{% load bootstrap4 %}
{% load i18n %}
{% load static %}
{% block content %}
{% if messages %}
<div class="position-message">
<ul class="message_ul notification message-box">
  {% for message in messages %}
  <li class="message_li notification-li">
    {{ message }}
    <i class="fas fa-trash delete"></i>
  </li>
  {% endfor %}
</ul>
</div>
{% endif %}
<div class="bg-white shadow rounded overflow-hidden contain-card-body">
  <div class="px-4 pt-0 pb-4 cover_">
      <div class="media align-items-end profile-head">
          <div class="media-body mb-5 text-white">
              <h4 class="mt-0 mb-0">{% trans "ToDo List" %}</h4>
              <p class="small mb-4"> <i class="fas fa-map-marker-alt mr-2"></i>LandLim</p>
          </div>
      </div>
  </div>
  <div class="card-box-top bg-light p-4 d-flex justify-content-end text-center">
      <ul class="list-inline mb-0">
          <li class="list-inline-item">
            <h5 class="font-weight-bold mb-0 d-block margin-h5" id="like_count">ToDo List</h5>
            <small class="text-muted">
              <i class="fas fa-list-ul sideicon"></i>
            </small>
          </li>
      </ul>
  </div>
  {% for do in todo %}
    <div class="px-4 card-box">
    <div class="p-4 rounded shadow-sm bg-light">
        <p class="mb-0 margin-p">
        {% if do.user.icon_url %}
            <a href="{% url 'accounts:others_page' do.user.pk %}"><img src="{{ do.user.icon_url }}" class="mb-2 circle"></a>
        {% else %}
            <a href="{% url 'accounts:others_page' do.user.pk %}"><img src="{% static 'icon/LandLim_Human.png' %}" class="mb-2 circle"></a>
        {% endif %}
        {{ do.text | safe }}
        <br><br><p class="list"><i class="fas fa-history"></i> {{ do.created_at }}
        <br><label><a class="red" href="{% url 'todolist:delete_todolist' do.pk %}"><i class="fas fa-trash"></i> {% trans "Delete ToDo" %}</a></label></p>
        </p>
    </div>
    </div>
  {% endfor %}
</div>
<style>
.profile-head {
  transform: translateY(5rem)
}
 .cover_ {
  background: linear-gradient(-15.5deg, #BE8200 20%, #FFB400 20% 40%, #009600 40% 60%, #006400 60% 80%);
  background-size: cover;
  background-repeat: no-repeat
}
.column {
  display: inline;
  flex-direction: column;
}
.green {
  color: #006400;
}
.red {
  color: #FF3333;
}
.image_tm {
  object-fit: cover;
  width: 327.5px;
  height: 327.5px;
  margin: 3.5px;
}
.material-icons {
  font-size: 13.5px;
}
.sideicon {
  font-size: 20.5px;
  color: #006400;
}
.list-inline-item {
  text-align: right !important;
}
.margin-h5 {
  margin-bottom: 5.5px !important;
}
.list {
    text-align: right;
}
</style>
{% block extend_js %}
<script src="{% static 'js/message.js' %}"></script>
{% endblock %}
{% endblock %}

landlim/templates/want_todo/want_todo_map.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load i18n %}
{% load static %}
{% block content %}
{% if messages %}
<div class="position-message">
<ul class="message_ul notification message-box">
  {% for message in messages %}
  <li class="message_li notification-li">
    {{ message }}
    <i class="fas fa-trash delete"></i>
  </li>
  {% endfor %}
</ul>
</div>
{% endif %}
<div class="bg-white shadow rounded overflow-hidden contain-card-body">
  <div class="px-4 pt-0 pb-4 cover_">
      <div class="media align-items-end profile-head">
          <div class="media-body mb-5 text-white">
              <h4 class="mt-0 mb-0">ToDo Map</h4>
              <p class="small mb-4"> <i class="fas fa-map-marker-alt mr-2"></i>LandLim</p>
          </div>
      </div>
  </div>
  <div class="bg-light p-4 d-flex justify-content-end text-center">
      <ul class="list-inline mb-0">
          <li class="list-inline-item">
            <h5 class="font-weight-bold mb-0 d-block margin-h5" id="like_count">Check ToDo Map</h5>
            <small class="text-muted">
              <i class="fas fa-map sideicon"></i>
            </small>
          </li>
      </ul>
  </div>
  <div class="px-1 py-3">
    <div class="row column">
      <div class="col-lg-12 mb-2">
        <div class="container" id="mapid"></div>
      </div>
    </div>
  </div>
</div>
<style>
.profile-head {
  transform: translateY(5rem)
}
 .cover_ {
  background: linear-gradient(-15.5deg, #BE8200 20%, #FFB400 20% 40%, #009600 40% 60%, #006400 60% 80%);
  background-size: cover;
  background-repeat: no-repeat
}
.column {
  display: inline;
  flex-direction: column;
}
.green {
  color: #006400;
}
.red {
  color: #FF3333;
}
.image_tm {
  object-fit: cover;
  width: 327.5px;
  height: 327.5px;
  margin: 3.5px;
}
.material-icons {
  font-size: 13.5px;
}
.sideicon {
  font-size: 20.5px;
  color: #006400;
}
.list-inline-item {
  text-align: right !important;
}
.margin-h5 {
  margin-bottom: 5.5px !important;
}
.todo-flex {
  padding-left: 3.35px;
  margin-bottom: 5.5px;
}
.todo-card {
  width: 205.05px;
  margin-bottom: 18.85px !important;
}
.todo-card .content .bttn {
  display: block;
  padding: 10px 25px;
  text-align: center;
  border-radius: 3px;
  background-color: #FF3333;
  text-decoration: none;
  color: #FFF;
  transition: 300ms all;
}
.todo-card .content .bttn:hover {
  background-color: #FF3333;
}
.list {
  text-align: right;
}
.little-p {
  font-size: 12.5px !important;
  text-align: right;
}
</style>
<script>
var mymap = L.map('mapid', {preferCanvas: true,});
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
minZoom: 8,
maxZoom: 19,
attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, '
}).addTo(mymap);
var pulsingIcon2 = L.icon.pulse({
iconSize:[20,20]
,color:'#006400'
,fillColor:'#009600'
,heartbeat: 2
});
function onLocationFound(e){
  L.Icon.Default.imagePath = 'https://unpkg.com/leaflet@1.3.1/dist/images/';
  L.marker(e.latlng, {icon:pulsingIcon2}).addTo(mymap);
}
function InputPinLocation(Location){
  const lat = Location.coords.longitude;
  const lng = Location.coords.latitude;
  var elem = document.getElementById("pin_x"); elem.innerHTML = "<input type='hidden' name='pin_x' id='id_pin_x' class='form-control' value = " + lat + ">";
  var elem = document.getElementById("pin_y"); elem.innerHTML = "<input type='hidden' name='pin_y' id='id_pin_y' class='form-control' value = " + lng + ">";
}
function onLocationError(e){
  alert("Could not retrieve current location. 現在地を取得できませんでした。" + e.message);
}
var data = [
  {% for i in todo %}
  {"loc": [{{ i.pin_x }}, {{ i.pin_y }}],
  "user": "{{ i.user }}",
  "text": "{{ i.text | safe }}",
  "created_at": "{{ i.created_at }}",
  "del_link": "{% url 'todolist:delete_todolist' i.pk %}"},
  {% endfor %}
];
for (i in data){
  var marker = L.marker(data[i].loc, { riseOnHover: true }).addTo(mymap);
  marker.bindPopup(`
    <div class="flex todo-flex">
    <div class="card todo-card">
    <div class="content">
    <div class="closebar">
    <h1>5 ways to create...</h1>
    <a href="#0" class="closebttn"><i class="material-icons">&#xE5CD;</i></a>
    </div>
    <p class="p">` + data[i].text + `</p>` +
    `<p class="p little-p">` + data[i].created_at + `</p>` +
    '<a style="font-size: 15.5px;" href="' + data[i].del_link + '" class="bttn">Delete ToDo</a>' + `
    </div>
    </div>
    </div>
  `);
}
mymap.on('locationfound', onLocationFound);
mymap.on('locationerror', onLocationError);
mymap.locate({setView: true, minZoom: 8, maxZoom: 19, timeout: 20000});
mymap.zoomControl.setPosition('bottomright');
mymap.sharelocationControl.setPosition('bottomright');
navigator.geolocation.getCurrentPosition(InputPinLocation,onLocationError);
</script>
{% block extend_js %}
<script src="{% static 'js/message.js' %}"></script>
{% endblock %}
{% endblock %}